/*
 * Author: Dimitrios Gkaltsidis (Original), Gemini (Modification)
 * Date: 27 Sept 2023 (Original) / Nov 10 2025 (Modification)
 * Disclaimer: This code is not fully optimized. For production-level 2D character functionality, consider crafting your own.
 * Version: 1.0.2 (Modified for Timed Block)
 * Note: Death and related inputs/logic have been removed. All other inputs are now public KeyCodes.
 * Block is now a timed action, not a hold action.
 */

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class OldHunter_PixelArt : MonoBehaviour
{
    private Rigidbody2D rb2D;
    private Animator animator;

    // VFX
    [SerializeField] GameObject vfxObject;

    // --- PUBLIC KEY INPUTS (InspectorПЁМ­ МГСЄ АЁДЩ) ---
    [Header("Input Key Bindings")]
    public KeyCode jumpKey = KeyCode.Space;
    public KeyCode rollKey = KeyCode.E;
    public KeyCode getHitKey = KeyCode.T;
    public KeyCode blockKey = KeyCode.Q;
    public KeyCode attackKey = KeyCode.P;
    public KeyCode specialAttackKey = KeyCode.O;
    // ПђСїРг ХА(A, D)ДТ Input.GetAxis("Horizontal")РЛ ЛчПыЧЯЙЧЗЮ КАЕЕ KeyCodeДТ КвЧЪПфЧеДЯДй.

    // Animation names for animator
    private string idleAnim = "Idle";
    private string runAnim = "Run";
    private string jumpAnim = "Jump";
    private string rollAnim = "Roll";
    private string hurtAnim = "Hurt";
    private string blockAnim = "Block";
    private string blockImpactAnim = "BlockImpact";
    private string attack1Anim = "Attack1";
    private string attack2Anim = "Attack2";
    private string attack3Anim = "Attack3";
    private string specialAttack = "SpecialAttack";

    // Movement variables
    private float moveSpeed = 8f;
    private bool isRunningLeft;
    private bool isRunningRight;

    // Jumping variables
    private float jumpForce = 8f;
    [SerializeField] LayerMask groundLayer;
    [SerializeField] Transform groundCheckTransform;
    [SerializeField] float groundCheckRadius = 0.2f;

    // Rolling variables
    private float rollForce = 25f;

    // --- MODIFICATION START ---
    [Header("Action Settings")]
    [Tooltip("ИЗБт(Block)АЁ РкЕПРИЗЮ ЧиСІЕЧБтБюСі АЩИЎДТ НУАЃ(УЪ)")]
    [SerializeField] private float blockDuration = 0.5f; // ИЗБт СіМг НУАЃ
    // --- MODIFICATION END ---

    // Other variables
    private bool isGrounded;
    private bool isHoldingBlock;
    private bool canContinueAttackCombo;
    private int currentAttackAnim;

    // Can receive input
    private bool canReceiveInput;

    private void Start()
    {
        rb2D = GetComponent<Rigidbody2D>();
        animator = GetComponent<Animator>();
        canReceiveInput = true;
        isHoldingBlock = false;
        canContinueAttackCombo = false;
        currentAttackAnim = 0;
    }

    private void Update()
    {
        GetMoveInput();
        GetJumpInput();
        GetRollInput();
        GetGetHitInput();
        GetHoldBlockInput();
        GetAttackInput();
        GetSpecialAttackInput();
        FlipSprite();
    }

    private void FixedUpdate()
    {
        Run();
        CheckIfGrounded();
    }

    #region INPUTS
    private void GetMoveInput()
    {
        if (canReceiveInput)
        {
            float moveForce = (Input.GetAxis("Horizontal"));

            if (moveForce < 0)
            {
                isRunningLeft = true;
                isRunningRight = false;
            }
            else if (moveForce > 0)
            {
                isRunningRight = true;
                isRunningLeft = false;
            }

            // Input.GetAxisДТ ХАИІ ЖМЕЕ М­М­Шї 0РИЗЮ ЕЙОЦПРЙЧЗЮ, ХАИІ Д­ЗЖДТСі ИэНУРћРИЗЮ ШЎРЮЧЯПЉ ИиУу УГИЎИІ ЧеДЯДй.
            if (!Input.GetKey(KeyCode.A) && !Input.GetKey(KeyCode.D))
            {
                StopMovement();
            }
        }
    }
    private void GetJumpInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(jumpKey))
            {
                if (isGrounded)
                {
                    Jump();
                }
            }
        }
    }
    private void GetRollInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(rollKey))
            {
                Roll();
            }
        }
    }
    private void GetGetHitInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(getHitKey))
            {
                GetHit();
            }
        }
    }

    // --- MODIFICATION START ---
    private void GetHoldBlockInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(blockKey))
            {
                HoldBlock();
            }
        }
        else
        {
            // КэЗЯ Сп КэЗЯ РгЦбЦЎ УГИЎДТ canReceiveInputРЬ falseРЯ ЖЇЕЕ АЁДЩЧиОп ЧеДЯДй.
            if (isHoldingBlock && Input.GetKeyDown(rollKey)) // Зб ХА(E)ИІ КэЗЯ РгЦбЦЎ ХзНКЦЎПыРИЗЮ ШАПы
            {
                GetHitWhileBlocking();
            }
            
            // Input.GetKeyUp(blockKey)ЗЮ EndBlocking()РЛ ШЃУтЧЯДј ЗЮСїРЛ СІАХЧпНРДЯДй.
            // РЬСІ HoldBlock() ГЛКЮРЧ InvokeАЁ РкЕПРИЗЮ EndBlocking()РЛ ШЃУтЧеДЯДй.
        }
    }
    // --- MODIFICATION END ---

    private void GetAttackInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(attackKey))
            {
                Attack();
            }
        }
        else
        {
            // АјАн Сп ПЌАш РдЗТРК canReceiveInputРЬ falseРЯ ЖЇЕЕ ЙоОЦОп ЧеДЯДй.
            if (Input.GetKeyDown(attackKey) && canContinueAttackCombo)
            {
                Attack();
            }
        }
    }
    private void GetSpecialAttackInput()
    {
        if (canReceiveInput)
        {
            if (Input.GetKeyDown(specialAttackKey))
            {
                SpecialAttack();
            }
        }
    }

    private void ReEnableInput()
    {
        canReceiveInput = true;
    }
    #endregion

    #region IDLE & RUN LOGIC
    private void Run()
    {
        // ... (Run ЗЮСїРК КЏАц ОјРН)
        if (isRunningLeft)
        {
            rb2D.velocity = new Vector2(-moveSpeed, rb2D.velocity.y);
            if (canReceiveInput)
            {
                animator.Play(runAnim);
            }
        }
        else if (isRunningRight)
        {
            rb2D.velocity = new Vector2(moveSpeed, rb2D.velocity.y);
            if (canReceiveInput)
            {
                animator.Play(runAnim);
            }
        }
        else if (!isRunningLeft && !isRunningRight && canReceiveInput)
        {
            if (canReceiveInput)
            {
                animator.Play(idleAnim);
            }
        }
    }
    private void StopMovement()
    {
        // ... (StopMovement ЗЮСїРК КЏАц ОјРН)
        if (isRunningLeft || isRunningRight)
        {
            rb2D.velocity = new Vector2(0, rb2D.velocity.y);
        }

        isRunningLeft = false;
        isRunningRight = false;
    }
    #endregion

    #region JUMPING LOGIC
    private void Jump()
    {
        canReceiveInput = false;
        rb2D.velocity = new Vector2(rb2D.velocity.x, jumpForce);
        animator.Play(jumpAnim);
        InvokeRepeating("EndJump", 0.1f, 0.1f);
    }
    private void EndJump()
    {
        if (isGrounded)
        {
            ReEnableInput();
            CancelInvoke();
        }
    }
    private void CheckIfGrounded()
    {
        isGrounded = Physics2D.OverlapCircle(groundCheckTransform.position, groundCheckRadius, groundLayer);
    }
    #endregion

    #region ROLLING LOGIC
    private void Roll()
    {
        canReceiveInput = false;
        StopMovement();
        rb2D.velocity = new Vector2(rollForce * GetPlayerDirection(), rb2D.velocity.y);
        animator.Play(rollAnim);
        // ОжДЯИоРЬМЧ РЬКЅЦЎГЊ InvokeИІ ЛчПыЧЯПЉ ReEnableInput() ШЃУт ЧЪПф
    }
    #endregion

    #region GETHIT LOGIC
    private void GetHit()
    {
        canReceiveInput = false;
        StopMovement();
        animator.Play(hurtAnim);
        // ОжДЯИоРЬМЧ РЬКЅЦЎГЊ InvokeИІ ЛчПыЧЯПЉ ReEnableInput() ШЃУт ЧЪПф
    }
    #endregion

    #region HOLDBLOCK LOGIC

    // --- MODIFICATION START ---
    private void HoldBlock()
    {
        isHoldingBlock = true;
        canReceiveInput = false;
        StopMovement();
        animator.Play(blockAnim);

        // blockDuration (ПЙ: 0.5УЪ) ШФПЁ EndBlockingРЛ ШЃУтЧЯПЉ ИЗБтИІ РкЕПРИЗЮ ЧиСІЧеДЯДй.
        Invoke("EndBlocking", blockDuration);
    }
    // --- MODIFICATION END ---

    private void GetHitWhileBlocking()
    {
        // EndBlockingРЛ ШЃУтЧЯДТ InvokeАЁ ПЙОрЕЧОю РжДйИщ УыМвЧеДЯДй.
        // (ЧЧАн РгЦбЦЎ ОжДЯИоРЬМЧРЬ ГЁГЊАэ ContinueBlockingРЬГЊ EndBlockingРЬ 
        //  ОжДЯИоРЬМЧ РЬКЅЦЎЗЮ ШЃУтЕЩ АЭРЛ ПЙЛѓ)
        CancelInvoke("EndBlocking");
        animator.Play(blockImpactAnim);
    }
    private void ContinueBlocking()
    {
        // BlockImpact ОжДЯИоРЬМЧРЬ ГЁГ­ ШФ ДйНУ Block ОжДЯИоРЬМЧРЛ РчЛ§Чв ЖЇ ШЃУтЕЫДЯДй.
        // (РЬ ЧдМіАЁ ОжДЯИоРЬМЧ РЬКЅЦЎЗЮ ПЌАсЕЧОю РжДйАэ АЁСЄ)
        // timed blockРИЗЮ КЏАцЕЧОњРИЙЧЗЮ, ПЉБтМ­ ДйНУ EndBlocking ХИРЬИгИІ АЩ Мі РжНРДЯДй.
        // ЧЯСіИИ, ПјЗЁ ЗЮСї(HoldBlock)РЛ УжДыЧб РЏСіЧЯБт РЇЧи ПЉБтМ­ДТ ОжДЯИоРЬМЧИИ РчЛ§ЧеДЯДй.
        // ИИОр BlockImpact ШФПЁЕЕ ДйНУ СЄЧиСј НУАЃИИХ­ ИЗБтИІ ПјЧбДйИщ
        // ПЉБтМ­ Invoke("EndBlocking", blockDuration); ИІ ДйНУ ШЃУтЧиОп ЧеДЯДй.
        animator.Play(blockAnim);

        // BlockImpact ШФПЁЕЕ СЄЧиСј НУАЃИИХ­ ИЗБтИІ РЏСіЧЯЕЕЗЯ МіСЄЧеДЯДй.
        Invoke("EndBlocking", blockDuration);
    }
    private void EndBlocking()
    {
        // ДйИЅ Invoke ШЃУтПЁ РЧЧи РЬЙЬ EndBlockingРЬ НЧЧрЕЧОњРЛ Мі РжРИЙЧЗЮ,
        // isHoldingBlock ЛѓХТИІ ШЎРЮЧеДЯДй.
        if (isHoldingBlock)
        {
            ReEnableInput();
            isHoldingBlock = false;
        }
    }
    #endregion

    #region ATTACK LOGIC
    private void Attack()
    {
        if (!canContinueAttackCombo)
        {
            canReceiveInput = false;
            StopMovement();
            currentAttackAnim = 0;
            DisableCanContinueAttackCombo();
            animator.Play(attack1Anim);
            currentAttackAnim++;
        }
        else
        {
            if (currentAttackAnim == 0) // РЬ КЮКаРК УЙ АјАнРЬ ГЁГ­ ШФ ComboАЁ trueРЯ ЖЇИИ НЧЧрЕЧОюОп ЧЯСіИИ, ПјКЛ ЗЮСїРЛ РЏСі
            {
                DisableCanContinueAttackCombo();
                animator.Play(attack1Anim);
                currentAttackAnim++;
            }
            else if (currentAttackAnim == 1)
            {
                DisableCanContinueAttackCombo();
                animator.Play(attack2Anim);
                currentAttackAnim++;
            }
            else if (currentAttackAnim == 2)
            {
                DisableCanContinueAttackCombo();
                animator.Play(attack3Anim);
                currentAttackAnim = 0;
            }
        }
    }
    private void EnableCanContinueAttackCombo()
    {
        canContinueAttackCombo = true;
    }
    private void DisableCanContinueAttackCombo()
    {
        canContinueAttackCombo = false;
    }
    #endregion

    #region SPECIAL ATTACK LOGIC
    private void SpecialAttack()
    {
        canReceiveInput = false;
        StopMovement();
        animator.Play(specialAttack);
        // ОжДЯИоРЬМЧ РЬКЅЦЎГЊ InvokeИІ ЛчПыЧЯПЉ ReEnableInput() ШЃУт ЧЪПф
    }
    #endregion

    #region SPAWN VFX OBJECT
    private void SpawnVFX()
    {
        GameObject myVfx = Instantiate(vfxObject);
        myVfx.transform.position = gameObject.transform.position;
        myVfx.transform.localScale = gameObject.transform.localScale;
    }
    #endregion

    private float GetPlayerDirection()
    {
        return transform.localScale.x;
    }

    private void FlipSprite()
    {
        if (rb2D.velocity.x < 0)
        {
            transform.localScale = new Vector3(-1, 1, 1);
        }
        else if (rb2D.velocity.x > 0)
        {
            transform.localScale = new Vector3(1, 1, 1);
        }
    }
}